### PR TITLE
Updated the readme

### PR DESCRIPTION
**Pull request by boykoc**
- Added the reading list to the Readme to make it easy for people to use.
- Added more links on how to access the reading list.
- Added a url and [instructions ](https://github.com/paulmaltby3/digitalpolicyreadinglist/pull/1/commits/9bbb58f06fb633e7896e8a4900d80c41cae933a3) on making the readme a webpage via github pages to make it easier for people to read the list without feeling overwhelmed by github :) 
- Added contribution instructions

Let me know if you need help or have questions or think this is going away from your original goal.

### CODE REVIEW

**Comment by boykoc** [comment]
@paulmaltby3 this PR is conflicting now. Are there any pieces from this you would like me to re-submit as a new PR?   This is what it would roughly look like as a github page https://boykoc.github.io/digitalpolicyreadinglist/

**Comment by paulmaltby3** [comment]
@boykoc thank you, and also thank you for being patient. I've not done this before and I don't think I did it in the right way earlier -sorry. 

I wanted to just update a single list, so I'd suggest dropping the link to the googledoc and amending from 'download the reading list from' to 'view the reading list here' and link through to the .md version rather than downloading the .odt

Is the content on the readme and the separate page connected, so that I'd only have to update one version of the list? If not I suggest not duplicating; I figured some people would just want the list rather than the blurb which is why I separated it. I guess I could just cut out the blurb if you think it gets in the way?

**Comment by boykoc** [comment]
@paulmaltby3 No worries. There's no one right way I'd say :)

I like your new format and using .md and the list as a separate page. Now that it is converted to .md it should be relatively easy to keep up to date (I hope).

I personally like the blurb. It tells the story of how this came to be. And with the link at the top and bottom it's easy for people to jump straight in to the list.

I would suggest updating your settings for this repository to activate github pages on the master. It will allow you to share a link of the readme in a more typical webpage format. Everytime you update the files the page is automatically updated.

It may sound intimidating but I promise it's pretty simple:

- click the "settings" tab at the top of the page (by the code, pull request, etc tabs)
- scroll down to the bottom where the heading says "GitHub Pages"
- in the "Source" drop down select "master branch" from the drop down
- click save

then everyone can access the page without the github scarriness here: https://paulmaltby3.github.io/digitalpolicyreadinglist/

**Comment by boykoc** [comment]
Looks good, I'll close this PR.

**Comment by paulmaltby3** [comment]
Thanks

Have done that, you're right is much better without the scariness. :)

**Comment by paulmaltby3** [comment]
Should I delete the odt version (which is already out of date), or just leave it there?

**Comment by boykoc** [comment]
I'd suggest deleting it. Clean and clutter free.  Plus, it'll always be in the git history if really needed.

**Pull request closed without merging**
