### PR TITLE
Remove Google intermediary links

### PR DESCRIPTION
**Pull request by edent**
The conversion added in lots of Google links. This change makes all links point to original sources.

### CODE REVIEW

**Comment by boykoc** [comment]
LGTM

**Comment by edent** [comment]
I've also just committed changes to remove t.co links as well.

**Comment by boykoc** [comment]
This is a [converter](https://word-to-markdown.herokuapp.com) i used.  Needs to be in Word format first but took minor formatting afterwards.  Adding a reference.

**Comment by paulmaltby3** [comment]
@edent thanks for helping me tidy up :)

**Pull request merged**
